Repository alkemyTech/OT287-server, pull requests merged in 2022-09, with the labels that each got.

#12 [ENDPOINT] OT287-18 GET /organizations/:id/public
  controllers/entries.js
  controllers/organizations.js
  database/migrations/20220915122858-create-entry.js
  database/models/category.js
  database/models/entry.js
  database/models/organization.js
  database/models/slide.js
  routes/activities.js
  routes/entries.js
  routes/index.js
  routes/organizations.js
  services/activities.js
  services/entries.js
  services/organizations.js
Labels: endpoint

#26 [ENDPOINT] OT287-90 : GET /members all members route
  controllers/members.js
  routes/index.js
  routes/members.js
  services/members.js
Labels: endpoint

#27 [ENDPOINT] OT287-73: POST /contacts
  controllers/contacts.js
  middlewares/validations.js
  routes/contacts.js
  routes/index.js
  schemas/contacts.js
  services/contacts.js
Labels: endpoint

#19 [ENDPOINT] OT287-56: POST /news
  controllers/entries.js
  routes/entries.js
  schemas/entries.js
  services/entries.js
Labels: endpoint

#34 [ENDPOINT] - OT287-91 : POST /members
  controllers/members.js
  routes/members.js
  schemas/members.js
  services/members.js
Labels: endpoint

#31 [ENDPOINT] OT287-97: GET /categories endpoint
  controllers/categories.js
  routes/categories.js
  routes/index.js
  services/categories.js
Labels: endpoint

#33 [ENDPOINT] OT287-86: PUT /testimonials/:id
  controllers/testimonials.js
  routes/testimonials.js
  services/testimonials.js
Labels: endpoint

#32 [ENDPOINT] OT287-67: POST /activities
  controllers/activities.js
  routes/activities.js
  schemas/activities.js
  services/activities.js
Labels: endpoint

#30 [ENDPOINT] OT287-92: PUT /members/:id
  controllers/members.js
  routes/members.js
  services/members.js
Labels: endpoint

#36 [ENDPOINT] OT287-99: PUT /categories/:id
  controllers/categories.js
  routes/categories.js
  services/categories.js
Labels: endpoint

#29 [ENDPOINT] OT287-93: DELETE /members/:id
  controllers/members.js
  routes/members.js
  services/members.js
Labels: endpoint

#35 [ENDPOINT] OT287-74: GET /contacts
  controllers/contacts.js
  routes/contacts.js
  services/contacts.js
Labels: endpoint

#17 [ENDPOINT] OT287-33: POST /auth/register User Registration Endpoint
  controllers/users.js
  package-lock.json
  package.json
  routes/index.js
  routes/users.js
  schemas/users.js
  services/users.js
Labels: endpoint

#18 [ENDPOINT] OT287-85: POST /testimonials
  controllers/testimonials.js
  routes/index.js
  routes/testimonials.js
  schemas/testimonials.js
  services/testimonials.js
Labels: endpoint

#38 [ENDPOINT] OT287-100: DELETE /categories/:id
  controllers/categories.js
  routes/categories.js
  services/categories.js
Labels: endpoint

#46 [ENDPOINT] OT287-37: GET /auth/me
  controllers/users.js
  routes/auth.js
  routes/index.js
  routes/users.js
Labels: endpoint

#44 [ENDPOINT] OT287-33: POST - User registration - FIX
  database/migrations/20200921211634-create-user.js
  services/users.js
Labels: fix

#48 Fix error handling in users controller and service
  controllers/users.js
  services/users.js
Labels: fix

#47 [SERVICE-EMAIL] OT287-30 SendGrid
  .env.example
  package.json
  services/sendEmail.js
Labels: feature

#45 [Service-AWS] Setup Amazon S3 SDK
  .env.example
  package.json
  services/aws.js
Labels: feature

#43 [ENDPOINT] OT287-26: POST /auth/login
  controllers/users.js
  routes/auth.js
  routes/users.js
  schemas/users.js
  services/users.js
Labels: endpoint

#40 [ENDPOINT] OT287-54: GET /users
  controllers/users.js
  routes/index.js
  routes/users.js
  services/users.js
Labels: endpoint
